=== AlexSkorupsky/encyclopedia/encyclopedia/encyclopedia.dtd
<!DOCTYPE encyclopedia [
<!ELEMENT encyclopedia (ename, countOfSections, section+, user+, tag+, connection+, change+, image+)>
<ATTRLIST encyclopedia
  encyclopediaID ID>
  <!ELEMENT ename (#PCDATA)>
  <!ELEMENT countOfSections (#PCDATA)>
  <!ELEMENT section (sname, countOfArticles, article*)>
  <!ATTRLIST section
    sectionID ID
    encyclopediaID IDREFS>
    <!ELEMENT sname (#PCDATA)>
    <!ELEMENT countOfArticles (#PCDATA)>
      <!ELEMENT article (aname, content, lastChangeDate)>
      <!ATTRLIST article
        articleID ID
        sectionID IDREFS>
      <!ELEMENT aname (#PCDATA)>
      <!ELEMENT content (#PCDATA)>
      <!ELEMENT lastChangeDate (#PCDATA)>
  <!ELEMENT user (uname)>
  <!ATTRLIST user
    userID ID>
    <!ELEMENT uname (#PCDATA)>
  <!ELEMENT tag (keyword)>
  <!ATTRLIST tag
    tagID ID>
    <!ELEMENT keyword (#PCDATA)>
  <!ELEMENT connection ()>
  <!ATTRLIST connection
    connectionID ID
    articleID IDREFS
    tagID IDREFS>
  <!ELEMENT change (date, content)>
  <!ATTRLIST change
    changeID ID
    articleID IDREFS
    userID IDREFS>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT content (#PCDATA)>
  <!ELEMENT image (iname, url)>
  <!ATTRLIST image
    imageID ID
    articleID IDREFS>
    <!ELEMENT iname (#PCDATA)>
    <!ELEMENT url (#PCDATA)>
]>

=== AlexSkorupsky/encyclopedia/encyclopedia/encyclopedia.xml
<?xml version = "1.0" encoding="UTF-8" standalone = "no" ?>
<!-- <!DOCTYPE encyclopedia SYSTEM "encyclopedia.dtd"> -->
<encyclopedia encyclopediaID = "wiki"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="encyclopedia.xsd">
  <ename>Wikipedia</ename>
  <countOfSections>2</countOfSections>
  <section sectionID = "s1" encyclopediaID = "wiki">
    <sname>Math</sname>
    <countOfArticles>3</countOfArticles>
    <article articleID = "a1" sectionID = "s1">
      <aname>Article1</aname>
      <content>Content of Article1</content>
      <lastChangeDate>2018-10-09</lastChangeDate>
    </article>
    <article articleID = "a2" sectionID = "s1">
      <aname>Article2</aname>
      <content>Content of Article2</content>
      <lastChangeDate>2018-10-05</lastChangeDate>
    </article>
    <article articleID = "a3" sectionID = "s1">
      <aname>Article3</aname>
      <content>Content of Article3</content>
      <lastChangeDate>2018-10-06</lastChangeDate>
    </article>
  </section>
  <user userID = "u1">
    <uname>User1</uname>
  </user>
  <user userID = "u2">
    <uname>User2</uname>
  </user>
  <tag tagID = "t1">
    <keyword>#tag1</keyword>
  </tag>
  <tag tagID = "t2">
    <keyword>#tag2</keyword>
  </tag>
  <tag tagID = "t3">
    <keyword>#tag3</keyword>
  </tag>
  <connection connectionID = "c1" articleID = "a1, a2" tagID = "t1"/>
  <connection connectionID = "c2" articleID = "a1, a3" tagID = "t2"/>
  <connection connectionID = "c3" articleID = "a2, a2" tagID = "t3"/>
  <change changeID = "c1" articleID = "a2" userID = "u1">
    <date>2018-10-05</date>
    <content>Content of Article2</content>
  </change>
  <change changeID = "c2" articleID = "a3" userID = "u1">
    <date>2018-10-06</date>
    <content>Content of Article3</content>
  </change>
  <change changeID = "c3" articleID = "a1" userID = "u1">
    <date>2018-10-08</date>
    <content>Content of Article1</content>
  </change>
  <image imageID = "i1" articleID = "a1, a2">
    <iname>Image1</iname>
    <url>www.image1.jpg</url>
  </image>
  <image imageID = "i2" articleID = "a2, a3">
    <iname>Image2</iname>
    <url>www.image2.jpg</url>
  </image>
  <image imageID = "i3" articleID = "a3">
    <iname>Image3</iname>
    <url>www.image3.jpg</url>
  </image>
</encyclopedia>
